### ISSUE TITLE
Update to latest create-react-app

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova#35]
https://github.com/facebookincubator/create-react-app/releases

**Comment by andela-rekemezie** [comment]
@trevordmiller I would like to take this but are there caveats to it?

**Comment by trevordmiller** [comment]
Hi @andela-rekemezie thank you for your interest! Someone actually talked this already as part of https://github.com/trevordmiller/nova/pull/51; sorry I should have closed this as a duplicate. I'll close it now. Feel free to grab another open Nova issue if you would still like to help out. Thanks :)
