### ISSUE TITLE
Semantic aliases for colors would be appreciated.

### ISSUE THREAD

**Issue by bugpowder** [trevordmiller/nova#36]
Similarly to the palette shown in the Nova webpage, you could provide semantically named aliases for the various colours in the npm package, e.g. "background", "foreground", "type", "variable", "value", etc -- instead of referring to those with their colour names, e.g. nova.black (which isn't black) for the background.

This would make creating new themes for editors etc. easier, without having to go back and forth to check what color is supposed to be what.

Nice color theme otherwise (I wouldn't bother commenting if I didn't think so),
Thanks
N.

**Comment by trevordmiller** [comment]
Thanks for using Nova and for your feedback. Please see the response on a duplicate issue: https://github.com/trevordmiller/nova-colors/issues/20.

**Comment by trevordmiller** [comment]
Also, fyi, "black" is an ANSI variable (as are all the other key names other than the `decoration` object.

**Comment by bugpowder** [comment]
> Please see the response on a duplicate issue.

Ah, sorry, didn't check for duplicates.

> Also, fyi, "black" is a standard ANSI variable name for terminal colors (as are all the other key names other than the decoration object.

Yes, but Nova is aimed on editors and other environments as well. Besides, those are legacy baggage from the 70s, along with the matching escape codes, as we've long has 256 colors even in terminals, and now even 24bit color.

**Comment by trevordmiller** [comment]
I responded on the nova-colors related issue: https://github.com/trevordmiller/nova-colors/issues/20. Keeping this issue closed as it is a duplicate.
