### ISSUE TITLE
Why are `import` and `const` not the same color?

### ISSUE THREAD

**Issue by hgwood** [trevordmiller/nova#44]
I'm trying to understand the intentional part of the color scheme, and I'm a bit confused by the first screenshot featured on the website, which displays Javascript. It seems to me `import` and `const` are both keywords that play a similar role in the language, which is to declare a new identifier, but they are not the same color.

Sorry if I missed the place where this is documented.

**Comment by trevordmiller** [comment]
@hgwood Thanks for the feedback. In each plugin, the Nova colors are mapped to syntax groups by color meaning; the `normal.green` is used for "types", so `const`, `var`, `let` etc. `normal.magenta` is used for "global" (which I consider anything that could potentially be outside of the current file like browser/node globals, modules, `this` references etc.); if something is both a "type" and "global" (which you could argue is the case for module definitions), the global styles will be used as I feel it is beneficial to see at a glance what is being referenced outside of the current context of your code. Feel free to check out the source code for each Nova plugin to see how this works.

**Comment by hgwood** [comment]
I see. Thank you for your response.
