### ISSUE TITLE
Clarify contributing info

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova#49]
Make contributing info clearer.

EX:
- https://twitter.com/driesvints/status/782937780234096640
- https://github.com/trevordmiller/nova-colors/issues/18

**Comment by designfrontier** [comment]
Looks like the solution to this would be a contributing.md file? I'll put one together if that seems like a reasonable route to you @trevordmiller :-)

**Comment by trevordmiller** [comment]
@designfrontier Initially I wanted to keep all documentation aggregated on https://trevordmiller.github.io/nova with [consistent `Contributing` instructions](http://www.trevordmiller.com/nova/#Contributing) that worked across all repos; but I think you are right - having a `CONTRIBUTING.md` file in each [`nova-*` plugin repo](https://github.com/trevordmiller?page=1&tab=repositories&utf8=%E2%9C%93&q=nova) would better follow convention and allow customization. Feel free to do this for this `nova` (documentation website) repo and I'll take care of the other `nova-*` plugin repos. Thanks for your help :)

**Comment by trevordmiller** [comment]
I've tried to follow this setup for each `nova-*` repo (`npm start` + `npm test` + `npm run push -- {major/minor/patch` scripts):
![image](https://cloud.githubusercontent.com/assets/5497885/19082487/999f2da2-8a1b-11e6-98c4-274b519aedc7.png)

**Comment by designfrontier** [comment]
It's nice to have contrib steps in the repos :-)

I'll pull that in to some contributing.md files in the various repos... PRs inbound at some point today

**Comment by trevordmiller** [comment]
Ok thanks @designfrontier

**Comment by designfrontier** [comment]
Once we get this first one nailed down... it looks like all the other repos will use a similar one? So probably going to just use this one once you're happy with the wording/layout/etc.

I think that seems reasonable?

**Comment by trevordmiller** [comment]
@designfrontier Sounds great! Thank you. I'll review on the PR.

**Comment by designfrontier** [comment]
Looks like I have some cleanup to do based on the referenced conversation threads...

**Comment by trevordmiller** [comment]
> "Looks like I have some cleanup to do based on the referenced conversation threads..."
I added some link notes to the PR that should address the issues in the referenced threads.
