### ISSUE TITLE
Add error tracking

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova#53]
[Sentry](https://sentry.io/pricing/) free tier

**Comment by colindevs** [comment]
@trevordmiller I looked at the Sentry docs, and I have a couple questions:
1. Would you like to pull in `raven.min.js` (js client for Sentry) by CDN (script in `index.html`) or `npm install`?
2. Are there any specific context you want to add to make Sentry more efficient or does a simple setting up of Sentry suffice?

If just a basic set up is enough I'd be happy to get it set up and submit a PR (hacktoberfest surge!). If not, I'd love to learn more about Sentry and work with you to use the Raven API to implement some more specific and contextual error messages.

**Comment by colindevs** [comment]
Also, how should we handle the Sentry API key? Should I simply put a placeholder where it should be, reference a config file that is `.gitignore`d, or just leave it?

**Comment by trevordmiller** [comment]
I saw your PR; I'm currently busy. It will get back to you. Please wait before preceding as I have answers to your questions.

**Comment by trevordmiller** [comment]
Thank you for your interest and help!

**Comment by trevordmiller** [comment]
@colindevs 

I was planning on doing this task since it will be using my Sentry account (which is why I had assigned it to myself) but I'm happy you are interested and would love for you to take it on if you'd still like to :) To answer your questions:

> "1. Would you like to pull in raven.min.js (js client for Sentry) by CDN (script in index.html) or npm install?"
I would like to use ES2015 modules with the rest of the app so all code is in a single bundle and there are no extra network requests. So, something like:

```
$ npm install -S raven-js
```
Then create a new file: `src/utils/errors.js` and initialize set up Raven in it:
```
import Raven from 'raven-js';
export default (
  Raven
    .config('https://bc98438d44bf4683916400feb2e05693@sentry.io/104379')
    .install();
```

> "Also, how should we handle the Sentry API key? "

As shown in the `.config()` call above ^, this is my Sentry config key you need; it's ok that its public as it will show in the code which is open source and I have configured allowed domains in Client Security.

> "2. Are there any specific context you want to add to make Sentry more efficient or does a simple setting up of Sentry suffice?"

Just the default `.config(...).install()` will be good enough for this project; I just want to know about runtime exceptions users hit.

Does that all make sense? I've assigned the task to you now instead of me, but if you are no longer interested, let me know and I'll grab it again. Thanks!

**Comment by colindevs** [comment]
I won't be able to do it until tonight (East Coast, so another 12 hours) so if time is an issue it's all yours, but I'd be glad to submit another PR with all the changes you listed above!

**Comment by trevordmiller** [comment]
@colindevs No rush, go for it :)

**Comment by colindevs** [comment]
@trevordmiller I've got it all done, but am having issues when submitting the PR. Github Desktop is returning this error message: 
![screen shot 2016-10-07 at 9 17 56 pm](https://cloud.githubusercontent.com/assets/12850952/19209205/a0c99ed6-8cd3-11e6-8616-2c5316271da5.png)

**Comment by trevordmiller** [comment]
@colindevs Cool! When contributing to a project you are not an admin on, you need to "fork" the project first. See this for details: https://help.github.com/articles/fork-a-repo/

**Comment by colindevs** [comment]
@trevordmiller I know, and I looked into the problem some more. It is an issue with the Desktop Client, and there are several ways to fix it and several different possible problems that can be causing the error (I did fork the project, it wouldn't let me publish to my own fork or submit a pull request to you). It is either a problem with SSH keys or with Apple saving the wrong password into iCloud keychain, and I tried some solutions that didn't work. 
I'll just figure out how to make a pull request from the command line then!

**Comment by trevordmiller** [comment]
@colindevs No worries. From the command line just run `npm run push -- minor`, then enter your commit message in the screen that pops up and save the file (if it opens in vim type `i` then your commit message then `:wq`). Then on GitHub submit your pull request like normal :)

**Comment by colindevs** [comment]
Ok, thanks

**Comment by colindevs** [comment]
Ended up just brushing up on my (long forgotten) git skills and used git push origin error-tracking and then submitted the pull request online. I hope its what you wanted!

**Comment by colindevs** [comment]
(I also found out that my `origin` was set to your repo so had to change it to my fork, that may have caused the problem!)
