### ISSUE TITLE
Update to "Hyper" rename

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova#57]
HyperTerm is now Hyper

**Comment by vypr** [comment]
#58, #59, #60

#60 might not need to be changed, if the tag is still hyperterm-symbols.

**Comment by trevordmiller** [comment]
@vypr Thank you for your help! I've approved all three pull requests; I merged #58. If you could update your branch for #59 and #60, I'll merge them too :)

**Comment by vypr** [comment]
Updated, everything should be all set. :)

**Comment by trevordmiller** [comment]
Thank you @vypr! I've merged them all :)

**Comment by trevordmiller** [comment]
Added a few more places where Hyper should be updated; I took care of it:
https://github.com/trevordmiller/nova/pull/65
