### ISSUE TITLE
Just a clone of Material Theme color schemes

### ISSUE THREAD

**Issue by equinusocio** [trevordmiller/nova#69]
https://github.com/equinusocio/material-theme

**Comment by trevordmiller** [comment]
I don't understand what the point of this issue is? `nova-colors` has completely different color values than Material.

**Comment by equinusocio** [comment]
The UX is very similar, and the material theme UX is the most important thing for me, build an identical color scheme that have less saturation isn't a good thing. Think what you wan't, but this is the point. Bye 👍

**Comment by trevordmiller** [comment]
No need to troll and leave an issue, if you don't like Nova just use the themes you enjoy :)
