### ISSUE TITLE
very unfriendly for the colorblind

### ISSUE THREAD

**Issue by metasean** [trevordmiller/nova#78]
I love the idea of having dedicated color meanings across environments.  But for what it's worth, I would never use it because anyone that I shared my screen with who has colorblindness would be SOL, and about 1 in 12 men have some degree of colorblindness :-(  Just something for you to chew on.  (Along with my dangling preposition.)

e.g.:
http://colortest.it/protanopia:http://www.trevordmiller.com/nova/
http://colortest.it/deuteranopia:http://www.trevordmiller.com/nova/
http://colortest.it/tritanopia:http://www.trevordmiller.com/nova/

http://www.colour-blindness.com/general/prevalence/
https://nei.nih.gov/health/color_blindness/facts_about

**Comment by trevordmiller** [comment]
Yes, I agree; if you or those you work with struggle with colorblindness, I would recommend using another theme that has higher contrast; this theme is meant to be low contrast / pastel colored :)
